# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0003_auto_20190919_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
