# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0005_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login_and_reg_app.User'),
            preserve_default=False,
        ),
    ]
