# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0007_trips_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
